# Generated by Django 4.2.3 on 2025-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='assets/a.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
